function grf = createAPOGRFs(grf, left_torque, right_torque)

    % Make the labels.
    labels = {'apo_force_vx','apo_force_vy','apo_force_vz',...
        'apo_force_px','apo_force_py','apo_force_pz',...
        'apo_torque_x','apo_torque_y','apo_torque_z',...
        '1_apo_force_vx','1_apo_force_vy','1_apo_force_vz',...
        '1_apo_force_px','1_apo_force_py','1_apo_force_pz',...
        '1_apo_torque_x','1_apo_torque_y','1_apo_torque_z',...
        'apo_group_force_vx','apo_group_force_vy','apo_group_force_vz',...
        'apo_group_force_px','apo_group_force_py','apo_group_force_pz',...
        'apo_group_torque_x','apo_group_torque_y','apo_group_torque_z',...
        '1_apo_group_force_vx','1_apo_group_force_vy','1_apo_group_force_vz',...
        '1_apo_group_force_px','1_apo_group_force_py','1_apo_group_force_pz',...
        '1_apo_group_torque_x','1_apo_group_torque_y','1_apo_group_torque_z'};

    % Form the values.
    values = zeros(grf.NFrames, length(labels));
    values(1:end,1:8) = 0;
    values(1:end,9) = right_torque;
    values(1:end,10:17) = 0;
    values(1:end,18) = left_torque;
    values(1:end,19:26) = 0;
    values(1:end,27) = -right_torque;
    values(1:end,28:35) = 0;
    values(1:end,36) = -left_torque;

    % Create the modified GRF object. 
    grf.extend(labels, values);

end